version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'monthly'
  - package_manager: 'javascript'
    directory: '/example'
    update_schedule: 'monthly'
